let str = "string";
let num = 5;
const car = { type: "Fiat", model: "500", color: "white" };
let bool = true;
let nul = null;
let undef;
let sym2 = Symbol("foo");
console.log(str);
console.log(num);
console.log(car);
console.log(bool);
console.log(nul);
console.log(undef);
console.log(sym2);
